# 10장. 예외 처리
- 코루틴 빌더는 부모도 종료시키며, 취소된 부모는 자식들 모두를 취소시킨다.
    - 자식 코루틴에서 예외가 발생할 경우, 자기 자신을 취소하고 부모에게 예외를 전파한다.
    - 부모는 자기 자신과 자식들 모두를 취소하고 부모에게 예외를 전파한다.
    - 루트 코루틴일 경우 예외를 던지며 프로그램을 종료한다.
- 쌍방으로 예외가 전파되며, 정지되지 않는다면 계통 구조상 모든 코루틴이 취소된다.

## 코루틴 종료 멈추기

- 코루틴이 종료되기 전에 예외를 잡을 수 있다.
    - 코루틴은 잡으로 상호작용하기에 try-catch 문을 통해 코루틴을 래핑하는 것은 도움되지 않는다.

### SupervisorJob

- SuperVisorJob을 사용하면 자식에서 발생한 모든 예외를 무시할 수 있다.
    - 일반적으로 다수의 코루틴을 시작하는 스코프로 사용된다.

<p align="center">  <img src=https://github.com/woowacourse-study/2023-BookOverFlow/assets/81347125/a67ea10b-8b78-4460-897a-28366a770cb5 align="center" width="40%">  <img src=https://github.com/woowacourse-study/2023-BookOverFlow/assets/81347125/5b5d6125-96ea-4e8c-9969-cbcfcc60150a align="center" width="40%"></p>
- 다음 코드처럼 부모 코루틴의 인자로 사용하는 경우 크게 이득을 취할 수 없다.
- 1에서 정의된 launch가 SupervisorJob을 인자로 받는데, 이럴 경우 SupervisorJob은 단 하나의 자식만 가지기 때문에 예외를 처리하는 데 아무런 도움이 되지 않는다.
    - 심지어 부모-자식 관계도 끊어져 runBlocking으로 전파되지 않는다.

```kotlin
fun main(): Unit = runBlocking {
	// 이렇게 하지 마세요. 자식 코루틴 하나가 있고
	// 부모 코루틴이 없는 잡은 일반 잡과 동일하게 작동한다.
	launch(SupervisorJob()) { // 1
		launch {
			delay(1000)
			throw Error("Some error")
		}

		launch {
			delay(2000)
			println("Will not be printed")
		}
	}

	delay(3000)
}
// Exception...
```

- 같은 잡을 다수의 코루틴에서 컨텍스트로 사용하는 것이 좀 더 나은 방법이다.

```kotlin
fun main(): Unit = runBlocking {
	val job = SupervisorJob()
	launch(job) {
		delay(1000)
		throw Error("Some error")
	}
	launch(job) {
		delay(2000)
		println("Will be printed")
	}
	job.join()
}
// (1초 후)
// Exception...
// (1초 후)
// Will be printed
```

### supervisorScope

- 예외 전파를 막는 또 다른 방법은 코루틴 빌더를 supervisorScope로 래핑하는 것이다.
    - 다른 코루틴에서 발생한 예외를 무시하고 부모와의 연결을 유지한다는 점에서 아주 편리하다.
- supervisorScope는 단지 중단함수이며, 중단 함수 본체를 래핑하는 데 사용한다.
    - 일반적으로 서로 무관한 다수의 작업을 스코프내에서 실행할 때 사용한다.

```kotlin
fun main(): Unit = runBlocking {
	supervisorScope {
		launch {
			delay(1000)
			throw Error("Some error")
		}

		launch {
			delay(2000)
			println("Will be printed")
		}
	}
	delay(1000)
	println("Done")
}
// Exception...
// Will be printed
// (1초 후)
// Done

suspend fun notifyAnalytics(actions: List<UserAction>) = 
	supervisorScope {
		actions.forEach { action ->
			launch {
				notifyAnalytics(action_
			}
		}
	}
```

- 또 다른 방법으로 coroutineScope를 사용하는 것이다.
- 이 함수는 코루틴 빌더와 달리 부모에 영향을 미치는 대신 try-catch를 이용해 잡을 수 있는 예외를 던진다.
- supervisorScope는 withContext(SupervisorJob()) 으로 대체될 수 없다.
    - 잡은 상속되지 않는 유일한 컨텍스트이므로 불가능하다.
    - 해당 스코프함수의 인자로 넘겨줄 경우, withContext의 새로운 부모 잡은 supervisorJob이 되며, 이는 아무런 의미가 없다.

### await

- 예외가 발생할 경우, async 코루틴 빌더는 launch처럼 부모 코루틴을 종료하고 부모와 관련있는 다른 코루틴 빌더도 종료시킨다.
- supervisorJob 혹은 supervisorScope와 await를 함께 사용할 경우 다음과 같다.

```kotlin
class MyException: Throwable()

suspend fun main() = supervisorScope {
	val str1 = async<String> {
		delay(1000)
		throw MyException()
	}

	val str2 = async {
		delay(2000)
		"Text2"
	}

	try {
		println(str1.await())
	} catch (e: MyException) {
		println(e)
	}

	println(str2.await())
}
// MyException
// Text2
```

- 코루틴이 예외로 종료되었기 때문에 반환할 값이 없지만, await가 MyException을 던지게 되어 해당 예외가 출력된다.
- supervisorScope가 사용되었기 때문에 또 다른 async는 중단되지 않고 끝까지 실행된다.

### CancellationException은 부모까지 전파되지 않는다

- 예외가 CancellationException의 서브클래스라면 부모로 전파되지 않는다.
    - CancellationException은 그냥 현재 코루틴을 취소 시킬 뿐이다.
    - open Class 이므로 다른 클래스로 확장될 수 있다.

        ```kotlin
        object MyNonPropagatingException : CancellationException()
        
        suspend fun main(): Unit = coroutineScope {
        	launch { // 1
        		launch { // 2
        			delay(2000)
        			println("Will not be printed")
        		}
        		throw MyNonPropagatingException // 3
        	}
        	launch { // 4
        		delay(2000)
        		println("Will be printed")
        	}
        }
        // (2초 후)
        // Will be printed
        ```


### 코루틴 예외 핸들러

- CoroutineExceptionHandler 컨텍스트를 사용해 예외처리 행동을 정의할 수 있다.
    - 예외 전파를 중단시키지는 않지만, 예외가 발생했을 때 해야 할 것들(예외 스택 트레이스 등)을 정의하는 데 사용한다.

```kotlin
fun main(): Unit = runBlocking {
	val handler = 
		CoroutineExceptionHandler { ctx, exception ->
			println("Caught $exception")
		}
	val scope = CoroutineScope(SupervisorJob() + handler)
	scope.launch {
		delay(1000)
		throw Error("Some error")
	}

	scope.launch {
		delay(2000)
		throw Error("Will be printed")
	}

	delay(3000)
}
```

### 요약

- 예외 처리는 kotlinx.coroutines 라이브러리의 중요한 기능이다.