# 9장 취소

## 기본적인 취소

**cancel 메서드**

- Job 인터페이스가 가지고 있다
- 호출한 코루틴은 첫 번째 중단점에서 잡을 끝낸다.
- 잡이 자식을 가지고 있다면, 그들 또한 취소된다. 하지만 부모는 영향을 받지 않는다.
- 잡이 취소되면, 취소된 잡은 새로운 코루틴의 부모로 사용될 수 없다. 취소된 잡은 ‘Cancelling’ 상태가 되었다가 ‘Cancelled’ 상태로 바뀐다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		repeat(1000) { i ->
			delay(200)
			println("Printing $i")
		}
	}
 
	delay(1100)
	job.cancel()
	job.join()
	println("Cancelled successfully")
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

cancel 함수에 각기 다른 예외를 인자로 넣는 방법을 사용하면 취소된 원인을 명확하게 할 수 있다.

코루틴을 취소하기 위해 인자로 사용되는 예외는 반드시 **CancellationException의 서브타입**이어야 한다.

cancel이 호출된 뒤 다음 작업을 진행하기 전에 취소 과정이 완료되는 걸 기다리기 위해 join을 사용하는 것이 일반적이다. join을 호출하지 않으면 `경쟁 상태`가 될 수도 있다. 

```kotlin
suspend fun main() = coroutineScope {
	val job = launch {
		repeat(1000) { i ->
			delay(100)
			Thread.sleep(100) // 오래 걸리는 연산이라 가정한다.
			println("Printing $i")
		}
	}

	delay(1000)
	job.cancel()
	println("Cancelled successfully")
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Cancelled successfully
// Printing 4
```

job.join()을 추가하면 코루틴이 취소를 마칠 때까지 중단되므로 경쟁 상태가 발생하지 않는다.

```kotlin
suspend fun main() = coroutineScope {
	val job = launch {
		repeat(1000) { i ->
			delay(100)
			Thread.sleep(100) // 오래 걸리는 연산이라 가정한다.
			println("Printing $i")
		}
	}

	delay(1000)
	job.cancel()
	job.join()
	println("Cancelled successfully")
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully

```

```kotlin
// cancel과 join을 함게 호출할 수 있는 확장 함수
public suspend fun Job.cancelAndJoin() {
	cancel()
	return join()
}
```

위 방법은 잡에 딸린 수많은 코루틴을 한번에 취소할 때 자주 사용된다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		repeat(1000) { i ->
			delay(200)
			println("Printing $i")
		}
	}
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

안드로이드에서 모든 코루틴 취소하는 예시

```kotlin
class ProfileViewModel: ViewModel() {
	private val scope = 
		 CoroutineScope(Dispatchers.Main + SupervisorJob())
	
	fun onCreate() {
		scope.launch { loadUserData() }
	}
	
	override fun onCleared() {
		scope.coroutineContext.cancelChildren()
	}

	// ..
}
```

## 취소는 어떻게 작동하는가?

잡이 취소되면 ‘Cancelling’ 상태로 바뀐다. 상태가 바뀐 뒤 첫 번째 중단점에서 CancellationException 예외를 던진다. 

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			repeat(1000) { i -> 
				delay(200)
				println("Printing $i")
			}
		} catch (e: CancellationException) {
			println(e)
			throw e
		}
	}
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
	delay(1000)
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// JobCancellationException...
// Cancelled successfully

```

취소된 코루틴이 단지 멈추는 것이 아니라 내부적으로 예외를 사용해 취소된다.

finally 블록 안에서 모든 것을 정리할 수 있다.

대부분의 자원 정리 과정은 finally 블록에서 실행된다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(Random.nextLong(2000))
			println("Done")
		} finally {
			print("Will always be printed")
		}
	}
	delay(1000)
	job.cancelAndJoin()
}
// Will always be printed
// (또는)
// Done
// Will always be printed
```

## 취소 중 코루틴을 한 번 더 호출하기

코루틴은 모든 자원을 정리할 필요가 있는 한 계속해서 실행될 수 있다.

하지만 정리 과정 중에 중단을 허용하지는 않는다.

Job은 이미 ‘Cancelling’ 상태가 되었기 때문에 중단되거나 다른 코루틴을 시작하는 건 절대 불가능하다.

다른 코루틴을 시작하려고 하면 그냥 무시해 버린다.

중단하려고 하면 `CancellationException`을 던진다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(2000)
			println("Job is Done")
		} finally {
			println("Finally")
			launch { // 무시된다.
				println("Will not be printed")
			}
			delay(1000) // 여기서 예외가 발생한다.
			println("Will not be printed")
		}
	}
	delay(1000)
	job.cancelAndJoin()
	println("Cancel done")
}
// (1초 후)
// Finally
// Cancel done
```

코루틴이 이미 취소되었을 때 중단 함수를 반드시 호출해야 하는 경우도 있다.

이런 경우 함수 콜을 withContext(NonCancellable)로 포장하는 방법이 많이 사용된다.

→ 이렇게 하면 코드 블록의 컨텍스트를 바꾸는 것이다.

→ withContext 내부에서 취소될 수 없는 Job인 NonCancellable 객체를 사용한다.

→ 블록 내부에서 잡은 액티브 상태를 유지하며, 중단함수를 원하는 만큼 호출할 수 있다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(200)
			println("Coroutine finished")
		} finally {
			println("Finally")
			withContext(NonCancellable) {
				delay(1000L)
				println("Cleanup done")
			}
		}
	}
	delay(100)
	job.cancelAndJoin()
	println("Done")
}
// Finally
// Cleanup done
// Done
```

## invokeOnCompletion

**invokeOnCompletion**

- 자원을 해제하는 데 자주 사용되는 방법
- 잡이 ‘Completed’나 ‘Cancelled’와 같은 마지막 상태에 도달했을 때 호출될 핸들러를 지정하는 역할을 한다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		delay(1000)
	}
	job.invokeOnCompletion { exception: Throwable? ->
		println("Finished")
	}
	delay(400)
	job.cancelAndJoin()
}
// Finished
```

핸들러의 파라미터 중 하나인 예외의 종류

- 잡이 예외 없이 끝나면 null이 된다.
- 코루틴이 취소되었으면 CancellationException이 된다.
- 코루틴이 종료시킨 예외일 수 있다.

잡이 invokeOnCompletion이 호출되기 전에 완료되었으면 핸들러는 즉시 호출된다.

onCancelling과 invokeImmediately 파라미터를 사용하면 핸들러의 동작 방식을 변경할 수도 있다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		delay(Random.nextLong(2400))
		println("Finished")
	}
	delay(800)
	job.invokeOnCompletion { exception: Throwable? ->
		println("Will always be printed")
		println("The exception was: $exception")
	}
	delay(800)
	job.cancelAndJoin()
}
// Will always be printed
// The exception was:
// kotlinx.coroutines.JobCancellationException
// (또는)
// Finished
// Will always be printed
// The exception was null
```

invokeOnCompletion은 취소하는 중에 동기적으로 호출되며, 어떤 스레드에서 실행할지 결정할 수 없다.

## 중단될 수 없는 걸 중단하기

취소는 중단점에서 일어나기 때문에 중단점이 없으면 취소를 할 수 없다.

```kotlin
// 코루틴 내부에 중단점이 없기 때문에 취소할 수 없는 상황
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		repeat(1000) { i ->
			Thread.sleep(200) // 여기서 복잡한 연산이나
			// 파일을 읽는 등의 작업이 있다고 가정한다
			println("Printing $i")
		}
	}
	delay(1000)
	job.cancelAndJoin()
	println("Cancelled successfully")
	delay(1000)
}
// Printing 0
// Printing 1
// Printing 2
// ... (1000까지)
```

위 상황에 대처하는 방법

- yield() 주기적 호출
    - yield는 코루틴을 중단하고 즉시 재실행한다.
    - 중단점이 생겼기 때문에 취소(또는 디스패처를 사용해 스레드를 바꾸는 일)를 포함해 중단(또는 재실행) 중에 필요한 모든 작업을 할 수 있는 기회가 주어진다.
    
    ```kotlin
    suspend fun main(): Unit = coroutineScope {
    	val job = Job()
    	launch(job) {
    		repeat(1000) { i ->
    			Thread.sleep(200)
    			yield()
    			println("Printing $i")
    		}
    	}
    	delay(1100)
    	job.cancelAndJoin()
    	println("Cancelled successfully")
    	delay(1000)
    }
    // Printing 0
    // Printing 1 
    // Printing 2
    // Printing 3
    // Printing 4
    // Cancelled successfully
    ```
    
    - 중단 가능하지 않으면서 CPU 집약적이거나 시간 집약적인 연산들이 중단 함수에 있다면, 각 연산들 사이에 yield를 사용하는 것이 좋다.
    
    ```kotlin
    suspend fun cpuIntensiveOperations() = 
    	withContext(Dispatchers.Default) {
    		cpuIntensiveOperation1()
    		yield()
    		cpuIntensiveOperation2()
    		yield()
    		cpuIntensiveOperation3()
    }
    ```
    

- 잡의 상태를 추적
    - 코루틴 빌더 내부에서 this는 빌더의 스코프를 참조하고 있고 스코프는 coroutineContext 프로퍼티를 사용해 참조할 수 있는 컨텍스트를 가지고 있다.
    - 코루틴 잡(coroutineContext[Job] or coroutineContext.job)에 접근해 현재 상태가 무엇인지 확인할 수 있다.
    - 잡은 코루틴이 액티브한지 확인하는데 사용되므로 액티브 상태를 확인하는 간단한 함수 제공
    
    ```kotlin
    // 잡이 액티브한지 확인할 수 있고, 액티브하지 않을 때는 연산 중단할 수 있다.
    public val CoroutineScope.isActive: Boolean
    	get() = coroutineContext[Job]?.isActive ?: true
    ```
    
    ```kotlin
    suspend fun main(): Unit = coroutineScope {
    	val job = Job()
    	launch(job) {
    		do {
    			Thread.sleep(200)
    			println("Printing")
    		} while (isActive)
    	}
    	delay(1100)
    	job.cancelAndJoin() 
    	println("Cancelled successfully")
    }
    // Printing
    // Printing
    // Printing
    // Printing
    // Printing
    // Printing
    // Cancelled successfully
    // ? 얘는 왜 6번 출력
    ```
    

- Job이 액티브 상태가 아니면 CancellationException을 던지는 ensureActive() 함수를 사용할 수 있다.
    
    ```kotlin
    suspend fun main(): Unit = coroutineScope {
    	val job = Job()
    	launch(job) {
    		repeat(1000) { num ->
    			Thread.sleep(200)
    			ensureActive()
    			println("Printing $num")
    		}
    	}
    	delay(1100)
    	job.cancelAndJoin()
    	println("Cancelled successfully")
    }
    // Printing 0
    // Printing 1
    // Printing 2
    // Printing 3
    // Printing 4
    // Cancelled successfully
    ```
    

### ensureActive() vs yield()

- 두 함수 모두 다른 코루틴이 실행할 수 있는 기회를 준다는 점에서 결과는 비슷하지만, 둘은 매우 다르다.
- ensureActive()
    - CoroutineScope(또는 CoroutineContext나 Job)에서 호출되어야 한다.
    - 잡이 더 이상 액티브 상태가 아니면 예외를 던진다.
    - 좀 더 가벼워 더 선호되고 있다.
- yield()
    - 전형적인 최상위 중단 함수
    - 스코프가 필요하지 않기 때문에 일반적인 중단 함수에서도 사용될 수 있다.
    - 중단하고 재개하는 일을 하기 때문에 스레드 풀을 가진 디스패처를 사용하면 스레드가 바뀌는 문제가 생길 수 있다.
    - CPU 사용량이 크거나 스레드를 블로킹하는 중단함수에서 자주 사용된다.

## suspendCancellableCoroutine

suspendCoroutine과 비슷하지만, 컨티뉴에이션 객체를 몇가지 메서드가 추가된 CancellableContinuation<T>로 래핑한다.

`invokeOnCancellation` 메서드

- 코루틴이 취소되었을 때 행동을 정의하는데 사용
- 라이브러리의 실행을 취소하거나 자원을 해제할 때 주로 사용된다.

```kotlin
suspend fun someTask() = suspendCancellableCoroutine { cont ->
	cont.invokeOnCancellation {
		// 정리 작업을 수행
	}
	// 나머지 구현 부분
}
```

```kotlin
// Retrofit Call을 중단 함수로 래핑
suspend fun getOrganizationRepos {
	organization: String
): List<Repo> = 
	suspendCancellableCoroutine { continuation ->
		val orgReposCall = apiService
			.getOrganizationRepos(organization)
		orgReposCall.enqueue(object: Callback<List<Repo>> {
			override fun onResponse(
				call: Call<List<Repo>>,
				response: Response<List<Repo>>
			) {
				if(response.isSuccessful) {
					val body = response.body()
					if (body != null) {
						continuation.resume(body)
					} else {
						continuation.resumeWithException(
							ResponseWithEmptyBody
						)
					}
				} else {
					continuation.resumeWithException(
						ApiException(
							response.code(),
							response.message()
						)
					)
				}
			}

			override fun onFailure(
				call: Call<List<Repo>>,
				t: Throwable
			) {
				continuation.resumeWithException(t)
			}
		})
		continuation.invokeOnCancellation {
			orgReposCall.cancel()
		}
	}

```

CancellableContinuation<T>에서도 잡의 상태를 확인할 수 있으며, 컨티뉴에이션을 취소할 때 취소가 되는 원인을 추가적으로 제공할 수 있다.

### 요약

취소를 적절하게 사용하면 자원 낭비와 메모리 누수를 줄일 수 있다.
