# 9장. 취소

## 기본적인 취소

- Job 인터페이스는 취소하게 하는 cancel 메서드를 가지고 있다.
    - `cancel()` 호출 시, 호출한 코루틴은 첫 번째 중단점에서 잡을 끝낸다.
    - 잡이 자식을 가지고 있다면, 그들 또한 취소 된다. 하지만 부모는 영향을 받지 않는다.
    - 잡이 취소되면,  취소된 잡은 새로운 코루틴의 부모로 사용될 수 없다.
        - 취소된 잡은 ‘CANCELLING’이 되고 자식 코루틴 모두 취소되면 → ‘CANCELLED’ 로 바뀐다.
- cancel 함수에 각기 다른 예외를 인자로 넣는 방법을 사용하면 취소된 원인을 명확하게 할 수 있다.
    - 코루틴을 취소하기 위해서 사용되는 예외는 CancellationException이어야 하므로 반드시 CancellationException의 서브타입이어야 한다.
        - 부모 코루틴에 전파하지 않고 취소해야 하므로 반드시 해당 타입이어야 한다.
- `join()` 메서드를 사용해 취소를 기다린 후 코드를 재개한다.
    - 그렇지 않으면 경쟁상태가 될 수 있다.
    - kotlinx.coroutines 라이브러리는 `cancelAndJoin()` 메서드를 제공한다.
- `Job()` 팩토리 함수를 통해 생성된 잡 또한 같은 방법으로 취소하며, 잡에 딸린 수많은 코루틴을 한번에 취소할 때 자주 사용된다.
    - ex) 사용자가 뷰를 나갈 때, `cancelChildren()`  을 통해 모든 코루틴 취소 등..

## 취소는 어떻게 작동하는가?

- 잡이 취소되면 ‘CANCELLING’ 상태로 바뀐다.
- 상태가 변경되며 첫 번째 중단점에서 CancellationException 예외를 던진다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			repeat(1000) { i -> 
				delay(200)
				println("Printing $i")
			}
		} catch (e: CancellationException) {
			println(e)
			throw e
		}
	}
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
	delay(1000)
}
// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// JobCancellationException...
// Cancelled successfully
```

- 취소된 코루틴이 단지 멈추는 것이 아닌 내부적으로 예외를 사용해 취소된다.
- 따라서, finally 블록 안에서 후처리를 할 수 있다.

## 취소 중 코루틴을 한 번 더 호출하기

- 후처리 과정 중 코루틴은 모든 자원을 정리할 필요가 있는 한 계속해서 실행될 수 있다.
    - 후처리 과정 중에 Job은 이미 ‘CANCELLING’ 상태이기 때문에 중단을 허용하지는 않는다.
        - 중단을 시도하면 CancellationException 을 던진다.
    - 다른 코루틴을 시작하는것도 허용하지 않는다.
        - 시도한다면 그냥 무시한다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(2000)
			println("Job is Done")
		} finally {
			println("Finally")
			launch { // 무시된다.
				println("Will not be printed")
			}
			delay(1000) // 여기서 예외가 발생한다.
			println("Will not be printed")
		}
	}
	delay(1000)
	job.cancelAndJoin()
	println("Cancel done")
}
// (1초 후)
// Finally
// Cancel done
```

- 데이터베이스의 롤백과 같이 중단 함수를 반드시 호출해야 하는 경우 `withContext(NonCancellable)` 로 포장하는 방법을 많이 사용한다.
    - 코드 블록의 컨텍스트를 바꾸며, withContext 내부에서 취소될 수 없는 Job인 NonCancellable 객체를 사용한다.
        - 이 경우 새로운 블록(스코프) 내부에서 잡은 액티브 상태를 유지하며, 중단 함수를 원하는 만큼 호출할 수 있다.

## invokeOnCompletion

- 자원을 해제하는 데 자주 사용되는 또 다른 방법은 Job의 invokeOnCompletion 메서드를 호출하는 것이다.
    - `invokeOnCompletion()`  메서드는 잡이 ‘COMPLETED’ 나 ‘CANCELLED’와 같은 마지막 상태에 도달했을 때 호출될 핸들러를 지정하는 역할을 한다.

    ```kotlin
    suspend fun main(): Unit = coroutineScope {
    	val job = launch {
    		delay(1000)
    	}
    	job.invokeOnCompletion { exception: Throwable? ->
    		println("Finished")
    	}
    	delay(400)
    	job.cancelAndJoin()
    }
    // Finished
    ```

    - 핸들러의 파라미터 중 하나인 예외의 종류는 다음과 같다.
        - 잡이 예외 없이 끝나면 null 이 반환된다.
        - 코루틴이 취소되었으면 CancellationException 이 된다.
        - 코루틴을 종료시킨 예외일 수 있다.
    - 잡이 `invokeOnCompletion()` 이 호출되기 전에 완료되었으면 핸들러는 즉시 호출된다.
    - ‘onCancelling’과 ‘invokeImmdiately’ 파라미터를 사용하면 핸들러의 동작 방식을 변경할 수도 있다.
        - onCancelling: 디폴트는 ‘false’이며, ‘true’일 경우 ‘Cancelling’ 상태에서 호출된다.
        - invokeImmediately: 코루틴이 이미 원하는 상태일 때 핸들러가 지정되었다면 핸들러를 즉시 호출할지 여부를 결정하는 파라미터이다. 디폴트는 ‘true’이다.

    ```kotlin
    suspend fun main(): Unit = coroutineScope {
    	val job = launch {
    		delay(Random.nextLong(2400))
    		println("Finished")
    	}
    	delay(800)
    	job.invokeOnCompletion { exception: Throwable? ->
    		println("Will always be printed")
    		println("The exception was: $exception")
    	}
    	delay(800)
    	job.cancelAndJoin()
    }
    // Will always be printed
    // The exception was:
    // kotlinx.coroutines.JobCancellationException
    // (또는)
    // Finished
    // Will always be printed
    // The exception was null
    ```

    - invokeOnCompletion은 취소하는 중에 동기적으로 호출되며, 어떤 스레드에서 실행할지 결정할 수는 없다.

## 중단될 수 없는 걸 중단하기

- 취소는 중단점에서 일어나기 때문에 중단점이 없으면 취소를 할 수 없다.

```kotlin
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		repeat(1000) { i ->
			Thread.sleep(200) // 여기서 복잡한 연산이나
			// 파일을 읽는 등의 작업이 있다고 가정한다
			println("Printing $i")
		}
	}
	delay(1000)
	job.cancelAndJoin()
	println("Cancelled successfully")
	delay(1000)
}
// Printing 0
// Printing 1
// Printing 2
// ... (1000까지)
```

- 중단점이 없어 취소를 시킬 수 없는 경우, 첫번째로 `yield()` 를 주기적으로 호출하는 방법이 있다.
    - yield는 코루틴을 중단하고 즉시 재실행한다.
    - 중단점이 생겼기 때문에 취소(또는 디스패처를 사용해 스레드를 바꾸는 일) 을 포함해 중단(또는 재실행) 중에 필요한 모든 작업을 할 수 있는 기회가 주어진다.
    - 중단 되지 않는 무거운 연산 함수가 중단 함수에 있다면, 각 연산들 사이에 `yield()` 를 사용하는 것이 좋다.
        - 동일 디스패처 스레드 풀 내 다른 스레드로 작업 양보

        ```kotlin
            suspend fun cpuIntensiveOperations() = 
            	withContext(Dispatchers.Default) {
            		cpuIntensiveOperation1()
            		yield()
            		cpuIntensiveOperation2()
            		yield()
            		cpuIntensiveOperation3()
            }
        ```

- 두 번째로, 잡의 상태를 추적하는 것이다.
    - 코루틴 빌더 내부의 리시버는 빌더의 스코프를 참조한다.
    - 코루틴 컨텍스트에 참조 가능하므로, 코루틴 잡의 현재 상태를 파악할 수 있다.
        - 잡의 상태 함수를 참고한다.
    - 잡의 액티브 상태가 아닐 때 CancellationException을 던지는 `ensureActive()` 함수를 사용해도 된다.

    ```kotlin
        suspend fun main(): Unit = coroutineScope {
        	val job = Job()
        	launch(job) {
        		repeat(1000) { num ->
        			Thread.sleep(200)
        			ensureActive()
        			println("Printing $num")
        		}
        	}
        	delay(1100)
        	job.cancelAndJoin()
        	println("Cancelled successfully")
        }
        // Printing 0
        // Printing 1
        // Printing 2
        // Printing 3
        // Printing 4
        // Cancelled successfully
    ```

- 두 함수 모두 다른 코루틴이 실행할 수 있는 기회를 준다는 점에서 결과는 비슷하지만 차이가 있다.
    - `ensureActive()` 함수는 CoroutineScope, CoroutineContext, Job에서 호출되어야 한다.
        - 잡이 더 이상 액티브 상태가 아닐 경우 예외를 던지며, 일반적으로 좀더 가볍다.
    - `yeild()` 함수는 전형적인 최상위 중단 함수로 스코프가 필요하지 않기 때문에 일반적인 중단 함수에서도 사용될 수 있다.
        - 중단하고 재개하는 일을 하기 때문에 스레드 풀을 가진 디스패처를 사용하면 스레드가 바뀔수도 있다.

## suspendCancellableCoroutine

- 기존의 suspendCoroutine과 유사하지만, Continuation 객체를 CancellableContinuation 객체로 래핑하며 몇 가지 메서드가 추가되었다.
- 가장 중요한 메서드는 코루틴이 취소되었을 때 행동을 정의하는 invokeOnCancellation이다.

    ```kotlin
    suspend fun getOrganizationRepos {
    	organization: String
    ): List<Repo> = 
    	suspendCancellableCoroutine { continuation ->
    		val orgReposCall = apiService
    			.getOrganizationRepos(organization)
    		orgReposCall.enqueue(object: Callback<List<Repo>> {
    			override fun onResponse(
    				call: Call<List<Repo>>,
    				response: Response<List<Repo>>
    			) {
    				if(response.isSuccessful) {
    					val body = response.body()
    					if (body != null) {
    						continuation.resume(body)
    					} else {
    						continuation.resumeWithException(
    							ResponseWithEmptyBody
    						)
    					}
    				} else {
    					continuation.resumeWithException(
    						ApiException(
    							response.code(),
    							response.message()
    						)
    					)
    				}
    			}
    
    			override fun onFailure(
    				call: Call<List<Repo>>,
    				t: Throwable
    			) {
    				continuation.resumeWithException(t)
    			}
    		})
    		continuation.invokeOnCancellation {
    			orgReposCall.cancel()
    		}
    	}
    ```

- CancellableContinuation에서도 상태 프로퍼티를 사용해 잡의 상태를 확인할 수 있으며, 컨티뉴에이션을 취소할 때 취소가 되는 원인을 추가적으로 제공할 수 있다.