# 취소

- 스레드를 죽이는 방식은 연결을 닫고 자원을 해제하는 기회가 없기 때문에 최악의 취소 방식이다.

<br><br>

## 기본적인 취소

- Job 인터페이스는 취소하게 되는 cancel 메서드를 가지고 있다. 이를 호출하면 다음과 같은 효과를 가져온다.
    - 호출한 코루틴은 첫 번째 중단점에서 Job을 끝낸다.
    - Job이 자식을 가지고 있다면, 그들 또한 취소된다. 하지만 부모는 영향받지 않는다.
    - Job이 취소되면 취소된 Job은 새로운 코루틴의 부모로 사용될 수 없다. 취소된 Job은 Cancelling 상태가 되었다가 Cancelled 상태로 바뀐다.
    
    <aside>
    💡 Cancelling 상태에서 자식 Job들이 끝날 때까지 기다리고 모두 끝나게 되면 Cancelled 상태로 들어간다.
    
    </aside>
    
<br>

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
        repeat(1_000) { i ->
            delay(200)
            println("$i 출력")
        }
    }
    delay(1100)
    job.cancel()
    job.join()
    println("성공적으로 취소")
}
```

- 실행 결과
    
    ```kotlin
    0 출력
    1 출력
    2 출력
    3 출력
    4 출력
    성공적으로 취소
    ```
    
- cancel 함수에 각기 다른 예외를 인자로 넣는 방법을 사용하면 취소된 원인을 명확하게 할 수 있다.
- 코루틴을 취소하기 위해 사용되는 예외는 CancellationException이어야 하기 때문에 인자로 사용되는 예외는 반드시 CancellationException의 서브타입이어야 한다.
- **cancel이 호출된 뒤 다음 작업을 진행하기 전에 취소 과정이 완료되는걸 기다리기 위해 join을 사용**하지 않으면 경쟁상태가 될 수도 있다.

<br>

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
        repeat(1_000) { i ->
            delay(100)
            Thread.sleep(100)  // 오래 걸리는 연산
            println("$i 출력")
        }
    }
    delay(1000)
    job.cancel()
    println("성공적으로 취소")
}
```

- 실행 결과
    
    ```kotlin
    0 출력
    1 출력
    2 출력
    3 출력
    성공적으로 취소
    4 출력
    ```
    
- 위 코드에서 join을 호출하지 않기 때문에 ‘성공적으로 취소’ 뒤에 ‘4 출력’이 출력되는 것을 볼 수 있다.
- join을 cancel 뒤에 추가하면 코루틴이 취소를 마칠 때까지 중단되기 때문에 경쟁 상태가 발생하지 않는다.
- kotlinx.coroutines 라이브러리는 call과 join을 함께 호출할 수 있는 간단한 방법으로 cancelAndJoin 이라는 확장함수를 제공한다.

<br>

```kotlin
public suspend fun Job.cancelAndJoin() {
    cancel()
    return join()
}
```

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        repeat(1_000) { i ->
            delay(200)
            println("$i 출력")
        }
    }
    delay(1100)
    job.cancelAndJoin()
    println("성공적으로 취소")
}
```

- 실행 결과
    
    ```kotlin
    0 출력
    1 출력
    2 출력
    3 출력
    성공적으로 취소
    4 출력
    ```
    
- Job() 팩토리 함수로 생성된 잡은 같은 방법으로 취소될 수 있다. 이 방법은 잡에 딸린 수많은 코루틴을 한번에 취소할 때 자주 사용된다.
- 안드로이드에서 사용자가 뷰 창을 나갔을 때 그 뷰에서 시작된 모든 코루틴을 취소하는 경우 한번에 취소하는 기능은 유용하게 작용한다.

<br>

## 취소는 어떻게 동작하는가?

- Job이 취소되면 Cancelling 상태로 바뀐다.
- 상태가 바뀐 뒤 첫 번째 중단점에서 CancellationException 예외를 던진다. 예외는 try-catch를 통해 잡을 수 있지만 다시 던지는 것이 좋다.

<br>

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        try {
            repeat(1_000) { i ->
                delay(200)
                println("$i 출력")
            }
        } catch (e: CancellationException) {
            println(e)
            throw e
        }

    }
    delay(1100)
    job.cancelAndJoin()
    println("성공적으로 취소")
    delay(1000)
}
```

- 실행 결과
    
    ```kotlin
    0 출력
    1 출력
    2 출력
    3 출력
    4 출력
    kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@2ece79d5
    성공적으로 취소
    ```
    
- **취소된 코루틴이 멈추는 것이 아니라 내부적으로 예외를 사용해 취소되는 것임을 명심하자.**
- 따라서 finally 블록 안에서 파일이나 데이터베이스 연결을 닫는 등 모든 것을 정리할 수 있다.

<br><br>

## 취소 중 코루틴을 한 번 더 호출하기

- 코루틴은 모든 자원을 정리할 필요가 있는 한 계속해서 실행될 수 있지만 정리 과정 중 중단을 허용하지는 않는다.
- Job은 이미 Cancelling 상태가 되었기 때문에 중단되거나 다른 코루틴을 시작하는 것은 절대 불가능하다.
- 만약 다른 코루틴을 시작하려고 하면 그냥 무시해 버린다.
- 중단하려고 하면 CancellationException을 던진다.

<br>

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        try {
            delay(2000)
            println("잡 종료")
        } finally {
            println("Finally")
            launch {  // 무시된다
                println("출력되지 않음")
            }
            delay(1000)  // 예외 발생!
            println("출력되지 않음")
        }

    }
    delay(1000)
    job.cancelAndJoin()
    println("성공적으로 취소")
}
```

- 실행 결과
    
    ```kotlin
    (1초 뒤)
    Finally
    성공적으로 취소
    ```
    
<br>

- 코루틴이 이미 취소되었을 때 중단 함수를 반드시 호출해야 하는 경우도 있다. (데이터베이스의 변경 사항을 롤백하는 경우)
- 이런 경우 함수 콜을 withContext(NonCancellable)로 포장하는 방법이 많이 사용된다.
- 중요한 점은 코드 블록의 컨텍스트를 바꾼다는 것이다.
- withContext 내부에서는 취소될 수 없는 Job인 NonCancellable 객체를 사용한다. 따라서 블록 내부에서 Job은 액티브 상태를 유지하며, 중단 함수를 원하는 만큼 호출할 수 있다.

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        try {
            delay(200)
            println("코루틴 종료")
        } finally {
            println("Finally")
            withContext(NonCancellable) {
                delay(1000L)
                println("청소 완료")
            }
        }

    }
    delay(1000)
    job.cancelAndJoin()
    println("종료")
}
```

- 실행 결과
    
    ```kotlin
    코루틴 종료
    Finally
    청소 완료
    종료
    ```
    
<br><br>

## invokeOnCompletion

- 자원을 해제하는 데 자주 사용되는 또 다른 방법은 Job의 invokeOnCompletion 메서드를 호출하는 것이다.
- invokeOnCompletion 메서드는 Job이 Completed나 Cancelled와 같은 마지막 상태에 도달했을 때 호출될 핸들러를 지정하는 역할을 한다.

<br>

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
        delay(1000)
    }
    job.invokeOnCompletion { exception: Throwable? ->
        println("종료")
    }
    delay(400)
    job.cancelAndJoin()
}
```

- 실행 결과
    
    ```kotlin
    종료
    ```
    
- 핸들러의 파라미터 중 하나인 예외의 종류는 다음과 같다.
    - Job이 예외 없이 끝나면 null이 된다.
    - 코루틴이 취소되었으면 CancellationException이 된다.
    - 코루틴을 종료시킨 예외일 수 있다.
- Job이 invokeOnCompletion이 호출되기 전에 완료되었으면 핸들러는 즉시 호출된다.
- onCancelling과 invokeImmediately 파라미터를 사용하면 핸들러의 동작 방식을 변경할 수 있다.

<br>

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = launch {
        delay(Random.nextLong(2400))
        println("종료")
    }
    delay(800)
    job.invokeOnCompletion { exception: Throwable? ->
        println("항상 출력된다")
        println("예외 : $exception")
    }
    delay(800)
    job.cancelAndJoin()
}
```

- 실행 결과
    
    ```kotlin
    종료
    항상 출력된다
    예외 : null
    
    or
    
    항상 출력된다
    예외 : kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelled}@7f16f662
    ```
    
- invokeOnCompletion은 취소하는 중에 동기적으로 호출되며, 어떤 스레드에서 실행할지 결정할 수 없다.

<br><br>

## 중단될 수 없는 걸 중단하기

- **취소는 중단점에서 일어나기** 때문에 중단점이 없으면 취소를 할 수 없다.

<br>

```kotlin
suspend fun main(): Unit = coroutineScope {
    val job = Job()
    launch(job) {
        repeat(1_000) { i ->
            Thread.sleep(200)
            println("출력 $i")
        }
    }
    delay(1000)
    job.cancelAndJoin()
    println("성공적 종료")
    delay(1000)
}
```

- 실행 결과
    
    ```kotlin
    출력 0
    출력 1
    출력 2
    출력 3
    ...
    출력 999
    ```
    

- 1초 뒤에 실행이 취소되어야 함에도 실제로는 3분이 넘게 걸린다.
- 코루틴 내부에 중단점이 없기 때문에 취소할 수 없는 상황인 것이다.

<br>

- 이런 상황을 대처하는 방법은 몇 가지 존재한다.
    - yield 함수를 주기적으로 호출한다.
        - yield 는 코루틴을 중단하고 즉시 재실행한다.
        - 중단점이 생겼기 때문에 취소(디스패처를 사용해 스레드를 바꾸는 일)를 포함해 중단(또는 재실행) 중 필요한 모든 작업을 할 수 있는 기회가 주어진다.
        - 중단 가능하지 않으면서 CPU 집약적이거나 시간 집약적인 연산들이 중단 함수에 있다면, 각 연산들 사이에 yield를 사용하는 것이 좋다.
        
        ```kotlin
        suspend fun main(): Unit = coroutineScope {
            val job = Job()
            launch(job) {
                repeat(1_000) { i ->
                    Thread.sleep(200)
                    yield()
                    println("출력 $i")
                }
            }
            delay(1100)
            job.cancelAndJoin()
            println("성공적 종료")
            delay(1000)
        }
        ```
        
        - 실행 결과
            
            ```kotlin
            출력 0
            출력 1
            출력 2
            출력 3
            출력 4
            성공적 종료
            ```
            
    - Job의 상태를 추적한다.
        - 코루틴 빌더 내부에서 this는 빌더의 스코프를 참조하고 있다.
        - CoroutineScope는 coroutineContext 프로퍼티를 사용해 참조할 수 있는 컨텍스트를 가지고 있다. 따라서 코루틴 Job에 접근해 현재 상태가 무엇인지 확인할 수 있다.
        - Job은 코루틴이 액티브한지 확인하는데 사용되기 때문에 액티브 상태를 확인하는 간단한 함수를 제공한다.
        - isActive 프로퍼티를 사용해 Job이 액티브한지 확인할 수 있고 액티브하지 않을 때는 연산을 중단할 수 있다.
        
        ```kotlin
        suspend fun main(): Unit = coroutineScope {
            val job = Job()
            launch(job) {
                do {
                    Thread.sleep(200)
                    println("출력")
                } while (isActive)
            }
            delay(1100)
            job.cancelAndJoin()
            println("성공적 종료")
        }
        ```
        
        - 실행 결과
            
            ```kotlin
            출력
            출력
            출력
            출력
            출력
            출력
            성공적 종료
            ```
            
    - Job이 액티브 상태가 아니면 CancellationException을 던지는 ensureActive() 함수를 사용한다.
        
        ```kotlin
        suspend fun main(): Unit = coroutineScope {
            val job = Job()
            launch(job) {
                repeat(1_000) { i ->
                    Thread.sleep(200)
                    ensureActive()
                    println("출력 $i")
                }
            }
            delay(1100)
            job.cancelAndJoin()
            println("성공적 종료")
        }
        ```
        
        - 실행 결과
            
            ```kotlin
            출력 0
            출력 1
            출력 2
            출력 3
            출력 4
            성공적 종료
            ```
            
<br>

- yield와 ensureActive 모두 다른 코루틴이 실행할 수 있는 기회를 준다는 점에서 결과는 비슷하지만, 둘은 다르다.
    - ensureActive 함수는 CoroutineScope에서 호출되어야 한다. 함수가 하는 일은 Job이 더 이상 액티브 상태가 아니면 예외를 던지는 것이다.
    - yield 함수는 전형적인 최상위 중단 함수다. 스코프가 필요하지 않기 때문에 일반적인 중단 함수에서도 사용될 수 있다. 중단하고 재개하는 일을 하기 때문에 스레드 풀을 가진 디스패처를 사용하면 스레드가 바뀌는 문제가 생길 수 있다.
    - yield 는 CPU 사용량이 크거나 스레드를 블로킹하는 중단 함수에서 자주 사용된다.

<br><br>

## suspendCancellableCoroutine

- suspendCoroutine과 비슷하지만, Continuation 객체를 몇 가지 메서드가 추가된 CancellableContinuation<T>로 래핑한다.
- invokeOnCancellation
    - 이 메서드는 코루틴이 취소되었을 때 행동을 정의하는데 사용한다.
    - 이 메서드는 라이브러리의 실행을 취소하거나 자원을 해제할 때 주로 사용된다.
    - suspendCancellableCoroutine을 사용하려면 이 메서드를 필수로 작성해야 한다.
    ```kotlin
    suspend fun task() = suspendCancellableCoroutine { cont ->
    cont.invokeOnCancellation {
        // 정리 작업
    }
    // 나머지 구현
}
    ```

<br><br>

## 요약

- 취소는 코루틴의 아주 강력한 기능이다.
- 취소를 적절히 사용하면 자원 낭비와 메모리 누수를 줄일 수 있다.